### ISSUE TITLE
compile error.

### ISSUE THREAD

**Issue by sen0va** [Pritoj/ra-dp-strapi#3]
I just started to learn nodejs. Trying to connect react-admin to strapi api.
When I start react-admin with ra-dp-strapi I get this error:

Failed to compile.

./node_modules/strapi-sdk-javascript/build/module/lib/sdk.js
Module parse failed: Unexpected token (14:12)
You may need an appropriate loader to handle this file type.
|             baseURL,
|             paramsSerializer: qs.stringify,
|             ...requestConfig
|         });
|         this.storeConfig = {

What should I do?

**Comment by Pritoj** [comment]
Hi @sen0va,
This is related to [this issue](https://github.com/strapi/strapi-sdk-javascript/issues/12).

Long story short, instead of doing this
```
import Strapi from 'strapi-sdk-javascript';
```

Do this
```
import Strapi from 'strapi-sdk-javascript/build/main';
```

Hopefully it should work. Please note that docs are currently not up to date. Please DON'T pass the API url to the latest release.

**Comment by Pritoj** [comment]
Hi @sen0va,
If this worked, can we close this?
Cheers

**Comment by sen0va** [comment]
Sorry for late answer. I quit trying to use strapi. Did not try the fix yet. I'll try after finishing my project. Thank you for your help.
